# Generated by Django 5.2.6 on 2025-10-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('created_ut', models.DateTimeField(auto_now_add=True)),
                ('updated_ut', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_ut', models.DateTimeField(auto_now_add=True)),
                ('updated_ut', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='myapp.user')),
                ('users_who_likes', models.ManyToManyField(related_name='liked_books', to='myapp.user')),
            ],
        ),
    ]
