# Generated by Django 5.2.6 on 2025-10-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_ut',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updated_ut',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_ut',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_ut',
            new_name='updated_at',
        ),
    ]
