# Generated by Django 5.2.6 on 2025-10-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message_description',
            new_name='message_description',
        ),
    ]
