# Generated by Django 5.2.6 on 2025-10-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
