# Generated by Django 5.2.6 on 2025-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='no descriptions yet'),
            preserve_default=False,
        ),
    ]
