# Generated by Django 5.2.6 on 2025-10-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
